[package]
name = "Bean"
version = "0.0.1"
#published-at = "0x00"

[addresses]
bean = "0x00"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet" }